
import AuthProvider from '@components/AuthProvider';
import Footer from '@components/Footer';
import NavBar from '@components/NavBar';
import '@styles/globals.css';


export const metadata = {
  title: "Artikel Trainer",
  description: "Generated by create next app",
  icons: '/artikel-trainer-logo.png'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          <main className='main'>
            <NavBar />
            {children}
            <Footer/>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
